// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: monitoring.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK | NOT_READY
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion       string                 `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,3,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	SamplesSent     uint64                 `protobuf:"varint,4,opt,name=samples_sent,json=samplesSent,proto3" json:"samples_sent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *AgentInfo) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *AgentInfo) GetSamplesSent() uint64 {
	if x != nil {
		return x.SamplesSent
	}
	return 0
}

type CpuMetrics struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	LogicalCores uint32                 `protobuf:"varint,2,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	Load1        float64                `protobuf:"fixed64,3,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5        float64                `protobuf:"fixed64,4,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15       float64                `protobuf:"fixed64,5,opt,name=load15,proto3" json:"load15,omitempty"`
	// Per logical core utilization (0–100), same order as gopsutil percpu.
	PerCorePercent []float64 `protobuf:"fixed64,6,rep,packed,name=per_core_percent,json=perCorePercent,proto3" json:"per_core_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *CpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetrics) GetLogicalCores() uint32 {
	if x != nil {
		return x.LogicalCores
	}
	return 0
}

func (x *CpuMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *CpuMetrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *CpuMetrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *CpuMetrics) GetPerCorePercent() []float64 {
	if x != nil {
		return x.PerCorePercent
	}
	return nil
}

type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMb       float64                `protobuf:"fixed64,1,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb        float64                `protobuf:"fixed64,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	AvailableMb   float64                `protobuf:"fixed64,3,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	CachedMb      float64                `protobuf:"fixed64,4,opt,name=cached_mb,json=cachedMb,proto3" json:"cached_mb,omitempty"`
	SwapTotalMb   float64                `protobuf:"fixed64,5,opt,name=swap_total_mb,json=swapTotalMb,proto3" json:"swap_total_mb,omitempty"`
	SwapUsedMb    float64                `protobuf:"fixed64,6,opt,name=swap_used_mb,json=swapUsedMb,proto3" json:"swap_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryMetrics) GetTotalMb() float64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *MemoryMetrics) GetUsedMb() float64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *MemoryMetrics) GetAvailableMb() float64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *MemoryMetrics) GetCachedMb() float64 {
	if x != nil {
		return x.CachedMb
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotalMb() float64 {
	if x != nil {
		return x.SwapTotalMb
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedMb() float64 {
	if x != nil {
		return x.SwapUsedMb
	}
	return 0
}

type DiskMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mount            string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Device           string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	UsedGb           float64                `protobuf:"fixed64,3,opt,name=used_gb,json=usedGb,proto3" json:"used_gb,omitempty"`
	TotalGb          float64                `protobuf:"fixed64,4,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"`
	ReadBytesPerSec  float64                `protobuf:"fixed64,5,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	WriteBytesPerSec float64                `protobuf:"fixed64,6,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	ReadOpsPerSec    float64                `protobuf:"fixed64,7,opt,name=read_ops_per_sec,json=readOpsPerSec,proto3" json:"read_ops_per_sec,omitempty"`
	WriteOpsPerSec   float64                `protobuf:"fixed64,8,opt,name=write_ops_per_sec,json=writeOpsPerSec,proto3" json:"write_ops_per_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *DiskMetrics) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetUsedGb() float64 {
	if x != nil {
		return x.UsedGb
	}
	return 0
}

func (x *DiskMetrics) GetTotalGb() float64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

func (x *DiskMetrics) GetReadBytesPerSec() float64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteBytesPerSec() float64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetReadOpsPerSec() float64 {
	if x != nil {
		return x.ReadOpsPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteOpsPerSec() float64 {
	if x != nil {
		return x.WriteOpsPerSec
	}
	return 0
}

type NetworkMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName   string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytesPerSec   float64                `protobuf:"fixed64,2,opt,name=rx_bytes_per_sec,json=rxBytesPerSec,proto3" json:"rx_bytes_per_sec,omitempty"`
	TxBytesPerSec   float64                `protobuf:"fixed64,3,opt,name=tx_bytes_per_sec,json=txBytesPerSec,proto3" json:"tx_bytes_per_sec,omitempty"`
	RxPacketsPerSec float64                `protobuf:"fixed64,4,opt,name=rx_packets_per_sec,json=rxPacketsPerSec,proto3" json:"rx_packets_per_sec,omitempty"`
	TxPacketsPerSec float64                `protobuf:"fixed64,5,opt,name=tx_packets_per_sec,json=txPacketsPerSec,proto3" json:"tx_packets_per_sec,omitempty"`
	RxErrors        uint64                 `protobuf:"varint,6,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors        uint64                 `protobuf:"varint,7,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	RxDropped       uint64                 `protobuf:"varint,8,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxDropped       uint64                 `protobuf:"varint,9,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	RxBytesTotal    uint64                 `protobuf:"varint,10,opt,name=rx_bytes_total,json=rxBytesTotal,proto3" json:"rx_bytes_total,omitempty"`
	TxBytesTotal    uint64                 `protobuf:"varint,11,opt,name=tx_bytes_total,json=txBytesTotal,proto3" json:"tx_bytes_total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkMetrics) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkMetrics) GetRxBytesPerSec() float64 {
	if x != nil {
		return x.RxBytesPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetTxBytesPerSec() float64 {
	if x != nil {
		return x.TxBytesPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetRxPacketsPerSec() float64 {
	if x != nil {
		return x.RxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetTxPacketsPerSec() float64 {
	if x != nil {
		return x.TxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkMetrics) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NetworkMetrics) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NetworkMetrics) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

func (x *NetworkMetrics) GetRxBytesTotal() uint64 {
	if x != nil {
		return x.RxBytesTotal
	}
	return 0
}

func (x *NetworkMetrics) GetTxBytesTotal() uint64 {
	if x != nil {
		return x.TxBytesTotal
	}
	return 0
}

type ProcessMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryMb      float64                `protobuf:"fixed64,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessMetrics) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type MetricsEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CollectedAtUnixMs int64                  `protobuf:"varint,2,opt,name=collected_at_unix_ms,json=collectedAtUnixMs,proto3" json:"collected_at_unix_ms,omitempty"`
	Sequence          uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Host              *HostInfo              `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Cpu               *CpuMetrics            `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory            *MemoryMetrics         `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks             []*DiskMetrics         `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks          []*NetworkMetrics      `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"`
	TopProcesses      []*ProcessMetrics      `protobuf:"bytes,9,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	Agent             *AgentInfo             `protobuf:"bytes,10,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsEnvelope) Reset() {
	*x = MetricsEnvelope{}
	mi := &file_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsEnvelope) ProtoMessage() {}

func (x *MetricsEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsEnvelope.ProtoReflect.Descriptor instead.
func (*MetricsEnvelope) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsEnvelope) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MetricsEnvelope) GetCollectedAtUnixMs() int64 {
	if x != nil {
		return x.CollectedAtUnixMs
	}
	return 0
}

func (x *MetricsEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MetricsEnvelope) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *MetricsEnvelope) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricsEnvelope) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsEnvelope) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsEnvelope) GetNetworks() []*NetworkMetrics {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *MetricsEnvelope) GetTopProcesses() []*ProcessMetrics {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

func (x *MetricsEnvelope) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

var File_monitoring_proto protoreflect.FileDescriptor

const file_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x10monitoring.proto\x12\fpulsegrid.v1\"\x10\n" +
	"\x0eMetricsRequest\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x94\x01\n" +
	"\tAgentInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12+\n" +
	"\x12started_at_unix_ms\x18\x03 \x01(\x03R\x0fstartedAtUnixMs\x12!\n" +
	"\fsamples_sent\x18\x04 \x01(\x04R\vsamplesSent\"\xc4\x01\n" +
	"\n" +
	"CpuMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12#\n" +
	"\rlogical_cores\x18\x02 \x01(\rR\flogicalCores\x12\x14\n" +
	"\x05load1\x18\x03 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x04 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x05 \x01(\x01R\x06load15\x12(\n" +
	"\x10per_core_percent\x18\x06 \x03(\x01R\x0eperCorePercent\"\xc9\x01\n" +
	"\rMemoryMetrics\x12\x19\n" +
	"\btotal_mb\x18\x01 \x01(\x01R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x02 \x01(\x01R\x06usedMb\x12!\n" +
	"\favailable_mb\x18\x03 \x01(\x01R\vavailableMb\x12\x1b\n" +
	"\tcached_mb\x18\x04 \x01(\x01R\bcachedMb\x12\"\n" +
	"\rswap_total_mb\x18\x05 \x01(\x01R\vswapTotalMb\x12 \n" +
	"\fswap_used_mb\x18\x06 \x01(\x01R\n" +
	"swapUsedMb\"\x9f\x02\n" +
	"\vDiskMetrics\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x17\n" +
	"\aused_gb\x18\x03 \x01(\x01R\x06usedGb\x12\x19\n" +
	"\btotal_gb\x18\x04 \x01(\x01R\atotalGb\x12+\n" +
	"\x12read_bytes_per_sec\x18\x05 \x01(\x01R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\x06 \x01(\x01R\x10writeBytesPerSec\x12'\n" +
	"\x10read_ops_per_sec\x18\a \x01(\x01R\rreadOpsPerSec\x12)\n" +
	"\x11write_ops_per_sec\x18\b \x01(\x01R\x0ewriteOpsPerSec\"\xa7\x03\n" +
	"\x0eNetworkMetrics\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12'\n" +
	"\x10rx_bytes_per_sec\x18\x02 \x01(\x01R\rrxBytesPerSec\x12'\n" +
	"\x10tx_bytes_per_sec\x18\x03 \x01(\x01R\rtxBytesPerSec\x12+\n" +
	"\x12rx_packets_per_sec\x18\x04 \x01(\x01R\x0frxPacketsPerSec\x12+\n" +
	"\x12tx_packets_per_sec\x18\x05 \x01(\x01R\x0ftxPacketsPerSec\x12\x1b\n" +
	"\trx_errors\x18\x06 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\a \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\b \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\t \x01(\x04R\ttxDropped\x12$\n" +
	"\x0erx_bytes_total\x18\n" +
	" \x01(\x04R\frxBytesTotal\x12$\n" +
	"\x0etx_bytes_total\x18\v \x01(\x04R\ftxBytesTotal\"t\n" +
	"\x0eProcessMetrics\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x01R\bmemoryMb\"\xe5\x03\n" +
	"\x0fMetricsEnvelope\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12/\n" +
	"\x14collected_at_unix_ms\x18\x02 \x01(\x03R\x11collectedAtUnixMs\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12*\n" +
	"\x04host\x18\x04 \x01(\v2\x16.pulsegrid.v1.HostInfoR\x04host\x12*\n" +
	"\x03cpu\x18\x05 \x01(\v2\x18.pulsegrid.v1.CpuMetricsR\x03cpu\x123\n" +
	"\x06memory\x18\x06 \x01(\v2\x1b.pulsegrid.v1.MemoryMetricsR\x06memory\x12/\n" +
	"\x05disks\x18\a \x03(\v2\x19.pulsegrid.v1.DiskMetricsR\x05disks\x128\n" +
	"\bnetworks\x18\b \x03(\v2\x1c.pulsegrid.v1.NetworkMetricsR\bnetworks\x12A\n" +
	"\rtop_processes\x18\t \x03(\v2\x1c.pulsegrid.v1.ProcessMetricsR\ftopProcesses\x12-\n" +
	"\x05agent\x18\n" +
	" \x01(\v2\x17.pulsegrid.v1.AgentInfoR\x05agent2\xf7\x01\n" +
	"\x10PulsegridService\x12I\n" +
	"\n" +
	"GetMetrics\x12\x1c.pulsegrid.v1.MetricsRequest\x1a\x1d.pulsegrid.v1.MetricsEnvelope\x12N\n" +
	"\rStreamMetrics\x12\x1c.pulsegrid.v1.MetricsRequest\x1a\x1d.pulsegrid.v1.MetricsEnvelope0\x01\x12H\n" +
	"\vHealthCheck\x12\x1b.pulsegrid.v1.HealthRequest\x1a\x1c.pulsegrid.v1.HealthResponseB\\\n" +
	"\x1fcom.monitoring.backend.grpc.genB\x0fMonitoringProtoP\x01Z&github.com/pulsegrid/agent/internal/pbb\x06proto3"

var (
	file_monitoring_proto_rawDescOnce sync.Once
	file_monitoring_proto_rawDescData []byte
)

func file_monitoring_proto_rawDescGZIP() []byte {
	file_monitoring_proto_rawDescOnce.Do(func() {
		file_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)))
	})
	return file_monitoring_proto_rawDescData
}

var file_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_monitoring_proto_goTypes = []any{
	(*MetricsRequest)(nil),  // 0: pulsegrid.v1.MetricsRequest
	(*HealthRequest)(nil),   // 1: pulsegrid.v1.HealthRequest
	(*HealthResponse)(nil),  // 2: pulsegrid.v1.HealthResponse
	(*HostInfo)(nil),        // 3: pulsegrid.v1.HostInfo
	(*AgentInfo)(nil),       // 4: pulsegrid.v1.AgentInfo
	(*CpuMetrics)(nil),      // 5: pulsegrid.v1.CpuMetrics
	(*MemoryMetrics)(nil),   // 6: pulsegrid.v1.MemoryMetrics
	(*DiskMetrics)(nil),     // 7: pulsegrid.v1.DiskMetrics
	(*NetworkMetrics)(nil),  // 8: pulsegrid.v1.NetworkMetrics
	(*ProcessMetrics)(nil),  // 9: pulsegrid.v1.ProcessMetrics
	(*MetricsEnvelope)(nil), // 10: pulsegrid.v1.MetricsEnvelope
}
var file_monitoring_proto_depIdxs = []int32{
	3,  // 0: pulsegrid.v1.MetricsEnvelope.host:type_name -> pulsegrid.v1.HostInfo
	5,  // 1: pulsegrid.v1.MetricsEnvelope.cpu:type_name -> pulsegrid.v1.CpuMetrics
	6,  // 2: pulsegrid.v1.MetricsEnvelope.memory:type_name -> pulsegrid.v1.MemoryMetrics
	7,  // 3: pulsegrid.v1.MetricsEnvelope.disks:type_name -> pulsegrid.v1.DiskMetrics
	8,  // 4: pulsegrid.v1.MetricsEnvelope.networks:type_name -> pulsegrid.v1.NetworkMetrics
	9,  // 5: pulsegrid.v1.MetricsEnvelope.top_processes:type_name -> pulsegrid.v1.ProcessMetrics
	4,  // 6: pulsegrid.v1.MetricsEnvelope.agent:type_name -> pulsegrid.v1.AgentInfo
	0,  // 7: pulsegrid.v1.PulsegridService.GetMetrics:input_type -> pulsegrid.v1.MetricsRequest
	0,  // 8: pulsegrid.v1.PulsegridService.StreamMetrics:input_type -> pulsegrid.v1.MetricsRequest
	1,  // 9: pulsegrid.v1.PulsegridService.HealthCheck:input_type -> pulsegrid.v1.HealthRequest
	10, // 10: pulsegrid.v1.PulsegridService.GetMetrics:output_type -> pulsegrid.v1.MetricsEnvelope
	10, // 11: pulsegrid.v1.PulsegridService.StreamMetrics:output_type -> pulsegrid.v1.MetricsEnvelope
	2,  // 12: pulsegrid.v1.PulsegridService.HealthCheck:output_type -> pulsegrid.v1.HealthResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_monitoring_proto_init() }
func file_monitoring_proto_init() {
	if File_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitoring_proto_goTypes,
		DependencyIndexes: file_monitoring_proto_depIdxs,
		MessageInfos:      file_monitoring_proto_msgTypes,
	}.Build()
	File_monitoring_proto = out.File
	file_monitoring_proto_goTypes = nil
	file_monitoring_proto_depIdxs = nil
}
