// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: monitoring.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PulsegridService_GetMetrics_FullMethodName    = "/pulsegrid.v1.PulsegridService/GetMetrics"
	PulsegridService_StreamMetrics_FullMethodName = "/pulsegrid.v1.PulsegridService/StreamMetrics"
	PulsegridService_HealthCheck_FullMethodName   = "/pulsegrid.v1.PulsegridService/HealthCheck"
)

// PulsegridServiceClient is the client API for PulsegridService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PulsegridServiceClient interface {
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsEnvelope, error)
	StreamMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEnvelope], error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pulsegridServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPulsegridServiceClient(cc grpc.ClientConnInterface) PulsegridServiceClient {
	return &pulsegridServiceClient{cc}
}

func (c *pulsegridServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsEnvelope)
	err := c.cc.Invoke(ctx, PulsegridService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pulsegridServiceClient) StreamMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PulsegridService_ServiceDesc.Streams[0], PulsegridService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsRequest, MetricsEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulsegridService_StreamMetricsClient = grpc.ServerStreamingClient[MetricsEnvelope]

func (c *pulsegridServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PulsegridService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulsegridServiceServer is the server API for PulsegridService service.
// All implementations must embed UnimplementedPulsegridServiceServer
// for forward compatibility.
type PulsegridServiceServer interface {
	GetMetrics(context.Context, *MetricsRequest) (*MetricsEnvelope, error)
	StreamMetrics(*MetricsRequest, grpc.ServerStreamingServer[MetricsEnvelope]) error
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPulsegridServiceServer()
}

// UnimplementedPulsegridServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulsegridServiceServer struct{}

func (UnimplementedPulsegridServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsEnvelope, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedPulsegridServiceServer) StreamMetrics(*MetricsRequest, grpc.ServerStreamingServer[MetricsEnvelope]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedPulsegridServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPulsegridServiceServer) mustEmbedUnimplementedPulsegridServiceServer() {}
func (UnimplementedPulsegridServiceServer) testEmbeddedByValue()                          {}

// UnsafePulsegridServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulsegridServiceServer will
// result in compilation errors.
type UnsafePulsegridServiceServer interface {
	mustEmbedUnimplementedPulsegridServiceServer()
}

func RegisterPulsegridServiceServer(s grpc.ServiceRegistrar, srv PulsegridServiceServer) {
	// If the following call panics, it indicates UnimplementedPulsegridServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PulsegridService_ServiceDesc, srv)
}

func _PulsegridService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsegridServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsegridService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsegridServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PulsegridService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PulsegridServiceServer).StreamMetrics(m, &grpc.GenericServerStream[MetricsRequest, MetricsEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PulsegridService_StreamMetricsServer = grpc.ServerStreamingServer[MetricsEnvelope]

func _PulsegridService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulsegridServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PulsegridService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulsegridServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PulsegridService_ServiceDesc is the grpc.ServiceDesc for PulsegridService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PulsegridService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pulsegrid.v1.PulsegridService",
	HandlerType: (*PulsegridServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _PulsegridService_GetMetrics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PulsegridService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _PulsegridService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitoring.proto",
}
