// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: monitoring.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	JoinToken     string                 `protobuf:"bytes,6,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"` // required for unregistered hosts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentHello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Metrics
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_CommandResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricsEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricsEnvelope `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResult) isAgentMessage_Payload() {}

type Welcome struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	MetricsIntervalSeconds   uint32                 `protobuf:"varint,3,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Welcome) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetMetricsIntervalSeconds() uint32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

type Reject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reject) Reset() {
	*x = Reject{}
	mi := &file_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reject) ProtoMessage() {}

func (x *Reject) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reject.ProtoReflect.Descriptor instead.
func (*Reject) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *Reject) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Reject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigUpdate struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MetricsIntervalSeconds   uint32                 `protobuf:"varint,1,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigUpdate) GetMetricsIntervalSeconds() uint32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

func (x *ConfigUpdate) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentCommand) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type MonitorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MonitorMessage_Welcome
	//	*MonitorMessage_Reject
	//	*MonitorMessage_ConfigUpdate
	//	*MonitorMessage_Command
	Payload       isMonitorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorMessage) Reset() {
	*x = MonitorMessage{}
	mi := &file_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorMessage) ProtoMessage() {}

func (x *MonitorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorMessage.ProtoReflect.Descriptor instead.
func (*MonitorMessage) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *MonitorMessage) GetPayload() isMonitorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MonitorMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*MonitorMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *MonitorMessage) GetReject() *Reject {
	if x != nil {
		if x, ok := x.Payload.(*MonitorMessage_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

func (x *MonitorMessage) GetConfigUpdate() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*MonitorMessage_ConfigUpdate); ok {
			return x.ConfigUpdate
		}
	}
	return nil
}

func (x *MonitorMessage) GetCommand() *AgentCommand {
	if x != nil {
		if x, ok := x.Payload.(*MonitorMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isMonitorMessage_Payload interface {
	isMonitorMessage_Payload()
}

type MonitorMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type MonitorMessage_Reject struct {
	Reject *Reject `protobuf:"bytes,2,opt,name=reject,proto3,oneof"`
}

type MonitorMessage_ConfigUpdate struct {
	ConfigUpdate *ConfigUpdate `protobuf:"bytes,3,opt,name=config_update,json=configUpdate,proto3,oneof"`
}

type MonitorMessage_Command struct {
	Command *AgentCommand `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

func (*MonitorMessage_Welcome) isMonitorMessage_Payload() {}

func (*MonitorMessage_Reject) isMonitorMessage_Payload() {}

func (*MonitorMessage_ConfigUpdate) isMonitorMessage_Payload() {}

func (*MonitorMessage_Command) isMonitorMessage_Payload() {}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GoVersion       string                 `protobuf:"bytes,2,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	StartedAtUnixMs int64                  `protobuf:"varint,3,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	SamplesSent     uint64                 `protobuf:"varint,4,opt,name=samples_sent,json=samplesSent,proto3" json:"samples_sent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{10}
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *AgentInfo) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *AgentInfo) GetSamplesSent() uint64 {
	if x != nil {
		return x.SamplesSent
	}
	return 0
}

type CpuMetrics struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	LogicalCores uint32                 `protobuf:"varint,2,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	Load1        float64                `protobuf:"fixed64,3,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5        float64                `protobuf:"fixed64,4,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15       float64                `protobuf:"fixed64,5,opt,name=load15,proto3" json:"load15,omitempty"`
	// Per logical core utilization (0–100), same order as gopsutil percpu.
	PerCorePercent []float64 `protobuf:"fixed64,6,rep,packed,name=per_core_percent,json=perCorePercent,proto3" json:"per_core_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_monitoring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{11}
}

func (x *CpuMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetrics) GetLogicalCores() uint32 {
	if x != nil {
		return x.LogicalCores
	}
	return 0
}

func (x *CpuMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *CpuMetrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *CpuMetrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *CpuMetrics) GetPerCorePercent() []float64 {
	if x != nil {
		return x.PerCorePercent
	}
	return nil
}

type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMb       float64                `protobuf:"fixed64,1,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb        float64                `protobuf:"fixed64,2,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	AvailableMb   float64                `protobuf:"fixed64,3,opt,name=available_mb,json=availableMb,proto3" json:"available_mb,omitempty"`
	CachedMb      float64                `protobuf:"fixed64,4,opt,name=cached_mb,json=cachedMb,proto3" json:"cached_mb,omitempty"`
	SwapTotalMb   float64                `protobuf:"fixed64,5,opt,name=swap_total_mb,json=swapTotalMb,proto3" json:"swap_total_mb,omitempty"`
	SwapUsedMb    float64                `protobuf:"fixed64,6,opt,name=swap_used_mb,json=swapUsedMb,proto3" json:"swap_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_monitoring_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{12}
}

func (x *MemoryMetrics) GetTotalMb() float64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *MemoryMetrics) GetUsedMb() float64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *MemoryMetrics) GetAvailableMb() float64 {
	if x != nil {
		return x.AvailableMb
	}
	return 0
}

func (x *MemoryMetrics) GetCachedMb() float64 {
	if x != nil {
		return x.CachedMb
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotalMb() float64 {
	if x != nil {
		return x.SwapTotalMb
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedMb() float64 {
	if x != nil {
		return x.SwapUsedMb
	}
	return 0
}

type DiskMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mount            string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Device           string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	UsedGb           float64                `protobuf:"fixed64,3,opt,name=used_gb,json=usedGb,proto3" json:"used_gb,omitempty"`
	TotalGb          float64                `protobuf:"fixed64,4,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"`
	ReadBytesPerSec  float64                `protobuf:"fixed64,5,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	WriteBytesPerSec float64                `protobuf:"fixed64,6,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	ReadOpsPerSec    float64                `protobuf:"fixed64,7,opt,name=read_ops_per_sec,json=readOpsPerSec,proto3" json:"read_ops_per_sec,omitempty"`
	WriteOpsPerSec   float64                `protobuf:"fixed64,8,opt,name=write_ops_per_sec,json=writeOpsPerSec,proto3" json:"write_ops_per_sec,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_monitoring_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{13}
}

func (x *DiskMetrics) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetUsedGb() float64 {
	if x != nil {
		return x.UsedGb
	}
	return 0
}

func (x *DiskMetrics) GetTotalGb() float64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

func (x *DiskMetrics) GetReadBytesPerSec() float64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteBytesPerSec() float64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetReadOpsPerSec() float64 {
	if x != nil {
		return x.ReadOpsPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteOpsPerSec() float64 {
	if x != nil {
		return x.WriteOpsPerSec
	}
	return 0
}

type NetworkMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName   string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytesPerSec   float64                `protobuf:"fixed64,2,opt,name=rx_bytes_per_sec,json=rxBytesPerSec,proto3" json:"rx_bytes_per_sec,omitempty"`
	TxBytesPerSec   float64                `protobuf:"fixed64,3,opt,name=tx_bytes_per_sec,json=txBytesPerSec,proto3" json:"tx_bytes_per_sec,omitempty"`
	RxPacketsPerSec float64                `protobuf:"fixed64,4,opt,name=rx_packets_per_sec,json=rxPacketsPerSec,proto3" json:"rx_packets_per_sec,omitempty"`
	TxPacketsPerSec float64                `protobuf:"fixed64,5,opt,name=tx_packets_per_sec,json=txPacketsPerSec,proto3" json:"tx_packets_per_sec,omitempty"`
	RxErrors        uint64                 `protobuf:"varint,6,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors        uint64                 `protobuf:"varint,7,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	RxDropped       uint64                 `protobuf:"varint,8,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxDropped       uint64                 `protobuf:"varint,9,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	RxBytesTotal    uint64                 `protobuf:"varint,10,opt,name=rx_bytes_total,json=rxBytesTotal,proto3" json:"rx_bytes_total,omitempty"`
	TxBytesTotal    uint64                 `protobuf:"varint,11,opt,name=tx_bytes_total,json=txBytesTotal,proto3" json:"tx_bytes_total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_monitoring_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkMetrics) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkMetrics) GetRxBytesPerSec() float64 {
	if x != nil {
		return x.RxBytesPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetTxBytesPerSec() float64 {
	if x != nil {
		return x.TxBytesPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetRxPacketsPerSec() float64 {
	if x != nil {
		return x.RxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetTxPacketsPerSec() float64 {
	if x != nil {
		return x.TxPacketsPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkMetrics) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NetworkMetrics) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NetworkMetrics) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

func (x *NetworkMetrics) GetRxBytesTotal() uint64 {
	if x != nil {
		return x.RxBytesTotal
	}
	return 0
}

func (x *NetworkMetrics) GetTxBytesTotal() uint64 {
	if x != nil {
		return x.TxBytesTotal
	}
	return 0
}

type ProcessMetrics struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pid        int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryMb   float64                `protobuf:"fixed64,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Ppid       int32                  `protobuf:"varint,5,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User       string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	// RUNNING | SLEEPING | ZOMBIE | STOPPED | IDLE | UNKNOWN
	State            string  `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	ThreadCount      uint32  `protobuf:"varint,8,opt,name=thread_count,json=threadCount,proto3" json:"thread_count,omitempty"`
	RssBytes         uint64  `protobuf:"varint,9,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	VmsBytes         uint64  `protobuf:"varint,10,opt,name=vms_bytes,json=vmsBytes,proto3" json:"vms_bytes,omitempty"`
	ReadBytesPerSec  float64 `protobuf:"fixed64,11,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	WriteBytesPerSec float64 `protobuf:"fixed64,12,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	StartTimeUnixMs  int64   `protobuf:"varint,13,opt,name=start_time_unix_ms,json=startTimeUnixMs,proto3" json:"start_time_unix_ms,omitempty"`
	// Truncated cmdline for stream (full command via GetProcessDetails later).
	Command       string `protobuf:"bytes,14,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_monitoring_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessMetrics) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessMetrics) GetMemoryMb() float64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ProcessMetrics) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessMetrics) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessMetrics) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessMetrics) GetThreadCount() uint32 {
	if x != nil {
		return x.ThreadCount
	}
	return 0
}

func (x *ProcessMetrics) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessMetrics) GetVmsBytes() uint64 {
	if x != nil {
		return x.VmsBytes
	}
	return 0
}

func (x *ProcessMetrics) GetReadBytesPerSec() float64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *ProcessMetrics) GetWriteBytesPerSec() float64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

func (x *ProcessMetrics) GetStartTimeUnixMs() int64 {
	if x != nil {
		return x.StartTimeUnixMs
	}
	return 0
}

func (x *ProcessMetrics) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ProcessSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Running       uint32                 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Sleeping      uint32                 `protobuf:"varint,3,opt,name=sleeping,proto3" json:"sleeping,omitempty"`
	Zombie        uint32                 `protobuf:"varint,4,opt,name=zombie,proto3" json:"zombie,omitempty"`
	Stopped       uint32                 `protobuf:"varint,5,opt,name=stopped,proto3" json:"stopped,omitempty"`
	Idle          uint32                 `protobuf:"varint,6,opt,name=idle,proto3" json:"idle,omitempty"`
	Other         uint32                 `protobuf:"varint,7,opt,name=other,proto3" json:"other,omitempty"`
	Threads       uint32                 `protobuf:"varint,8,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSummary) Reset() {
	*x = ProcessSummary{}
	mi := &file_monitoring_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSummary) ProtoMessage() {}

func (x *ProcessSummary) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSummary.ProtoReflect.Descriptor instead.
func (*ProcessSummary) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessSummary) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProcessSummary) GetRunning() uint32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *ProcessSummary) GetSleeping() uint32 {
	if x != nil {
		return x.Sleeping
	}
	return 0
}

func (x *ProcessSummary) GetZombie() uint32 {
	if x != nil {
		return x.Zombie
	}
	return 0
}

func (x *ProcessSummary) GetStopped() uint32 {
	if x != nil {
		return x.Stopped
	}
	return 0
}

func (x *ProcessSummary) GetIdle() uint32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *ProcessSummary) GetOther() uint32 {
	if x != nil {
		return x.Other
	}
	return 0
}

func (x *ProcessSummary) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type MetricsEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CollectedAtUnixMs int64                  `protobuf:"varint,2,opt,name=collected_at_unix_ms,json=collectedAtUnixMs,proto3" json:"collected_at_unix_ms,omitempty"`
	Sequence          uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Host              *HostInfo              `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Cpu               *CpuMetrics            `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory            *MemoryMetrics         `protobuf:"bytes,6,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks             []*DiskMetrics         `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks          []*NetworkMetrics      `protobuf:"bytes,8,rep,name=networks,proto3" json:"networks,omitempty"`
	TopProcesses      []*ProcessMetrics      `protobuf:"bytes,9,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	Agent             *AgentInfo             `protobuf:"bytes,10,opt,name=agent,proto3" json:"agent,omitempty"`
	ProcessSummary    *ProcessSummary        `protobuf:"bytes,11,opt,name=process_summary,json=processSummary,proto3" json:"process_summary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsEnvelope) Reset() {
	*x = MetricsEnvelope{}
	mi := &file_monitoring_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsEnvelope) ProtoMessage() {}

func (x *MetricsEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_monitoring_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsEnvelope.ProtoReflect.Descriptor instead.
func (*MetricsEnvelope) Descriptor() ([]byte, []int) {
	return file_monitoring_proto_rawDescGZIP(), []int{17}
}

func (x *MetricsEnvelope) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MetricsEnvelope) GetCollectedAtUnixMs() int64 {
	if x != nil {
		return x.CollectedAtUnixMs
	}
	return 0
}

func (x *MetricsEnvelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MetricsEnvelope) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *MetricsEnvelope) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *MetricsEnvelope) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MetricsEnvelope) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsEnvelope) GetNetworks() []*NetworkMetrics {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *MetricsEnvelope) GetTopProcesses() []*ProcessMetrics {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

func (x *MetricsEnvelope) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *MetricsEnvelope) GetProcessSummary() *ProcessSummary {
	if x != nil {
		return x.ProcessSummary
	}
	return nil
}

var File_monitoring_proto protoreflect.FileDescriptor

const file_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x10monitoring.proto\x12\fpulsegrid.v1\"\xad\x01\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"join_token\x18\x06 \x01(\tR\tjoinToken\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\"X\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x85\x02\n" +
	"\fAgentMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.pulsegrid.v1.AgentHelloH\x00R\x05hello\x129\n" +
	"\ametrics\x18\x02 \x01(\v2\x1d.pulsegrid.v1.MetricsEnvelopeH\x00R\ametrics\x127\n" +
	"\theartbeat\x18\x03 \x01(\v2\x17.pulsegrid.v1.HeartbeatH\x00R\theartbeat\x12D\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2\x1b.pulsegrid.v1.CommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\x9d\x01\n" +
	"\aWelcome\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\rR\x18heartbeatIntervalSeconds\x128\n" +
	"\x18metrics_interval_seconds\x18\x03 \x01(\rR\x16metricsIntervalSeconds\"6\n" +
	"\x06Reject\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x01\n" +
	"\fConfigUpdate\x128\n" +
	"\x18metrics_interval_seconds\x18\x01 \x01(\rR\x16metricsIntervalSeconds\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\rR\x18heartbeatIntervalSeconds\"d\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"\xf9\x01\n" +
	"\x0eMonitorMessage\x121\n" +
	"\awelcome\x18\x01 \x01(\v2\x15.pulsegrid.v1.WelcomeH\x00R\awelcome\x12.\n" +
	"\x06reject\x18\x02 \x01(\v2\x14.pulsegrid.v1.RejectH\x00R\x06reject\x12A\n" +
	"\rconfig_update\x18\x03 \x01(\v2\x1a.pulsegrid.v1.ConfigUpdateH\x00R\fconfigUpdate\x126\n" +
	"\acommand\x18\x04 \x01(\v2\x1a.pulsegrid.v1.AgentCommandH\x00R\acommandB\t\n" +
	"\apayload\"f\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x94\x01\n" +
	"\tAgentInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"go_version\x18\x02 \x01(\tR\tgoVersion\x12+\n" +
	"\x12started_at_unix_ms\x18\x03 \x01(\x03R\x0fstartedAtUnixMs\x12!\n" +
	"\fsamples_sent\x18\x04 \x01(\x04R\vsamplesSent\"\xc4\x01\n" +
	"\n" +
	"CpuMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12#\n" +
	"\rlogical_cores\x18\x02 \x01(\rR\flogicalCores\x12\x14\n" +
	"\x05load1\x18\x03 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x04 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x05 \x01(\x01R\x06load15\x12(\n" +
	"\x10per_core_percent\x18\x06 \x03(\x01R\x0eperCorePercent\"\xc9\x01\n" +
	"\rMemoryMetrics\x12\x19\n" +
	"\btotal_mb\x18\x01 \x01(\x01R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x02 \x01(\x01R\x06usedMb\x12!\n" +
	"\favailable_mb\x18\x03 \x01(\x01R\vavailableMb\x12\x1b\n" +
	"\tcached_mb\x18\x04 \x01(\x01R\bcachedMb\x12\"\n" +
	"\rswap_total_mb\x18\x05 \x01(\x01R\vswapTotalMb\x12 \n" +
	"\fswap_used_mb\x18\x06 \x01(\x01R\n" +
	"swapUsedMb\"\x9f\x02\n" +
	"\vDiskMetrics\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x17\n" +
	"\aused_gb\x18\x03 \x01(\x01R\x06usedGb\x12\x19\n" +
	"\btotal_gb\x18\x04 \x01(\x01R\atotalGb\x12+\n" +
	"\x12read_bytes_per_sec\x18\x05 \x01(\x01R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\x06 \x01(\x01R\x10writeBytesPerSec\x12'\n" +
	"\x10read_ops_per_sec\x18\a \x01(\x01R\rreadOpsPerSec\x12)\n" +
	"\x11write_ops_per_sec\x18\b \x01(\x01R\x0ewriteOpsPerSec\"\xa7\x03\n" +
	"\x0eNetworkMetrics\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12'\n" +
	"\x10rx_bytes_per_sec\x18\x02 \x01(\x01R\rrxBytesPerSec\x12'\n" +
	"\x10tx_bytes_per_sec\x18\x03 \x01(\x01R\rtxBytesPerSec\x12+\n" +
	"\x12rx_packets_per_sec\x18\x04 \x01(\x01R\x0frxPacketsPerSec\x12+\n" +
	"\x12tx_packets_per_sec\x18\x05 \x01(\x01R\x0ftxPacketsPerSec\x12\x1b\n" +
	"\trx_errors\x18\x06 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\a \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\b \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\t \x01(\x04R\ttxDropped\x12$\n" +
	"\x0erx_bytes_total\x18\n" +
	" \x01(\x04R\frxBytesTotal\x12$\n" +
	"\x0etx_bytes_total\x18\v \x01(\x04R\ftxBytesTotal\"\xb2\x03\n" +
	"\x0eProcessMetrics\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x01R\bmemoryMb\x12\x12\n" +
	"\x04ppid\x18\x05 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12!\n" +
	"\fthread_count\x18\b \x01(\rR\vthreadCount\x12\x1b\n" +
	"\trss_bytes\x18\t \x01(\x04R\brssBytes\x12\x1b\n" +
	"\tvms_bytes\x18\n" +
	" \x01(\x04R\bvmsBytes\x12+\n" +
	"\x12read_bytes_per_sec\x18\v \x01(\x01R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\f \x01(\x01R\x10writeBytesPerSec\x12+\n" +
	"\x12start_time_unix_ms\x18\r \x01(\x03R\x0fstartTimeUnixMs\x12\x18\n" +
	"\acommand\x18\x0e \x01(\tR\acommand\"\xd2\x01\n" +
	"\x0eProcessSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\arunning\x18\x02 \x01(\rR\arunning\x12\x1a\n" +
	"\bsleeping\x18\x03 \x01(\rR\bsleeping\x12\x16\n" +
	"\x06zombie\x18\x04 \x01(\rR\x06zombie\x12\x18\n" +
	"\astopped\x18\x05 \x01(\rR\astopped\x12\x12\n" +
	"\x04idle\x18\x06 \x01(\rR\x04idle\x12\x14\n" +
	"\x05other\x18\a \x01(\rR\x05other\x12\x18\n" +
	"\athreads\x18\b \x01(\rR\athreads\"\xac\x04\n" +
	"\x0fMetricsEnvelope\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12/\n" +
	"\x14collected_at_unix_ms\x18\x02 \x01(\x03R\x11collectedAtUnixMs\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12*\n" +
	"\x04host\x18\x04 \x01(\v2\x16.pulsegrid.v1.HostInfoR\x04host\x12*\n" +
	"\x03cpu\x18\x05 \x01(\v2\x18.pulsegrid.v1.CpuMetricsR\x03cpu\x123\n" +
	"\x06memory\x18\x06 \x01(\v2\x1b.pulsegrid.v1.MemoryMetricsR\x06memory\x12/\n" +
	"\x05disks\x18\a \x03(\v2\x19.pulsegrid.v1.DiskMetricsR\x05disks\x128\n" +
	"\bnetworks\x18\b \x03(\v2\x1c.pulsegrid.v1.NetworkMetricsR\bnetworks\x12A\n" +
	"\rtop_processes\x18\t \x03(\v2\x1c.pulsegrid.v1.ProcessMetricsR\ftopProcesses\x12-\n" +
	"\x05agent\x18\n" +
	" \x01(\v2\x17.pulsegrid.v1.AgentInfoR\x05agent\x12E\n" +
	"\x0fprocess_summary\x18\v \x01(\v2\x1c.pulsegrid.v1.ProcessSummaryR\x0eprocessSummary2W\n" +
	"\fAgentGateway\x12G\n" +
	"\aConnect\x12\x1a.pulsegrid.v1.AgentMessage\x1a\x1c.pulsegrid.v1.MonitorMessage(\x010\x01B\\\n" +
	"\x1fcom.monitoring.backend.grpc.genB\x0fMonitoringProtoP\x01Z&github.com/pulsegrid/agent/internal/pbb\x06proto3"

var (
	file_monitoring_proto_rawDescOnce sync.Once
	file_monitoring_proto_rawDescData []byte
)

func file_monitoring_proto_rawDescGZIP() []byte {
	file_monitoring_proto_rawDescOnce.Do(func() {
		file_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)))
	})
	return file_monitoring_proto_rawDescData
}

var file_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_monitoring_proto_goTypes = []any{
	(*AgentHello)(nil),      // 0: pulsegrid.v1.AgentHello
	(*Heartbeat)(nil),       // 1: pulsegrid.v1.Heartbeat
	(*CommandResult)(nil),   // 2: pulsegrid.v1.CommandResult
	(*AgentMessage)(nil),    // 3: pulsegrid.v1.AgentMessage
	(*Welcome)(nil),         // 4: pulsegrid.v1.Welcome
	(*Reject)(nil),          // 5: pulsegrid.v1.Reject
	(*ConfigUpdate)(nil),    // 6: pulsegrid.v1.ConfigUpdate
	(*AgentCommand)(nil),    // 7: pulsegrid.v1.AgentCommand
	(*MonitorMessage)(nil),  // 8: pulsegrid.v1.MonitorMessage
	(*HostInfo)(nil),        // 9: pulsegrid.v1.HostInfo
	(*AgentInfo)(nil),       // 10: pulsegrid.v1.AgentInfo
	(*CpuMetrics)(nil),      // 11: pulsegrid.v1.CpuMetrics
	(*MemoryMetrics)(nil),   // 12: pulsegrid.v1.MemoryMetrics
	(*DiskMetrics)(nil),     // 13: pulsegrid.v1.DiskMetrics
	(*NetworkMetrics)(nil),  // 14: pulsegrid.v1.NetworkMetrics
	(*ProcessMetrics)(nil),  // 15: pulsegrid.v1.ProcessMetrics
	(*ProcessSummary)(nil),  // 16: pulsegrid.v1.ProcessSummary
	(*MetricsEnvelope)(nil), // 17: pulsegrid.v1.MetricsEnvelope
}
var file_monitoring_proto_depIdxs = []int32{
	0,  // 0: pulsegrid.v1.AgentMessage.hello:type_name -> pulsegrid.v1.AgentHello
	17, // 1: pulsegrid.v1.AgentMessage.metrics:type_name -> pulsegrid.v1.MetricsEnvelope
	1,  // 2: pulsegrid.v1.AgentMessage.heartbeat:type_name -> pulsegrid.v1.Heartbeat
	2,  // 3: pulsegrid.v1.AgentMessage.command_result:type_name -> pulsegrid.v1.CommandResult
	4,  // 4: pulsegrid.v1.MonitorMessage.welcome:type_name -> pulsegrid.v1.Welcome
	5,  // 5: pulsegrid.v1.MonitorMessage.reject:type_name -> pulsegrid.v1.Reject
	6,  // 6: pulsegrid.v1.MonitorMessage.config_update:type_name -> pulsegrid.v1.ConfigUpdate
	7,  // 7: pulsegrid.v1.MonitorMessage.command:type_name -> pulsegrid.v1.AgentCommand
	9,  // 8: pulsegrid.v1.MetricsEnvelope.host:type_name -> pulsegrid.v1.HostInfo
	11, // 9: pulsegrid.v1.MetricsEnvelope.cpu:type_name -> pulsegrid.v1.CpuMetrics
	12, // 10: pulsegrid.v1.MetricsEnvelope.memory:type_name -> pulsegrid.v1.MemoryMetrics
	13, // 11: pulsegrid.v1.MetricsEnvelope.disks:type_name -> pulsegrid.v1.DiskMetrics
	14, // 12: pulsegrid.v1.MetricsEnvelope.networks:type_name -> pulsegrid.v1.NetworkMetrics
	15, // 13: pulsegrid.v1.MetricsEnvelope.top_processes:type_name -> pulsegrid.v1.ProcessMetrics
	10, // 14: pulsegrid.v1.MetricsEnvelope.agent:type_name -> pulsegrid.v1.AgentInfo
	16, // 15: pulsegrid.v1.MetricsEnvelope.process_summary:type_name -> pulsegrid.v1.ProcessSummary
	3,  // 16: pulsegrid.v1.AgentGateway.Connect:input_type -> pulsegrid.v1.AgentMessage
	8,  // 17: pulsegrid.v1.AgentGateway.Connect:output_type -> pulsegrid.v1.MonitorMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_monitoring_proto_init() }
func file_monitoring_proto_init() {
	if File_monitoring_proto != nil {
		return
	}
	file_monitoring_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_CommandResult)(nil),
	}
	file_monitoring_proto_msgTypes[8].OneofWrappers = []any{
		(*MonitorMessage_Welcome)(nil),
		(*MonitorMessage_Reject)(nil),
		(*MonitorMessage_ConfigUpdate)(nil),
		(*MonitorMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitoring_proto_rawDesc), len(file_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitoring_proto_goTypes,
		DependencyIndexes: file_monitoring_proto_depIdxs,
		MessageInfos:      file_monitoring_proto_msgTypes,
	}.Build()
	File_monitoring_proto = out.File
	file_monitoring_proto_goTypes = nil
	file_monitoring_proto_depIdxs = nil
}
