# Pulsegrid Monitor installer for Windows (Docker Desktop required).
# Agents dial the Monitor Agent Gateway — use run-agent.ps1 / install-agent.sh.
param(
  [string]$PublicHost = "localhost",
  [int]$BackendPort = 8080,
  [int]$DashboardPort = 3000,
  [int]$GatewayPort = 50051,
  [string]$InstallDir = "",
  [switch]$Demo,
  [switch]$NoStart,
  # Deprecated (v2.0): ignored — agents dial Monitor
  [string]$Agents = ""
)

$ErrorActionPreference = "Stop"

if ($Agents) {
  Write-Warning "-Agents was removed in v2.0 (agents dial the Monitor). Ignoring."
}

if (-not $InstallDir) {
  $InstallDir = Split-Path -Parent $PSScriptRoot
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "docker is required (Docker Desktop)"
}

docker compose version | Out-Null

$certScript = Join-Path $PSScriptRoot "generate-monitor-certs.ps1"
if (Test-Path $certScript) {
  & $certScript -PublicHost $PublicHost -OutDir (Join-Path $InstallDir "certs")
} else {
  $bash = Join-Path $PSScriptRoot "generate-monitor-certs.sh"
  if (Get-Command bash -ErrorAction SilentlyContinue) {
    & bash $bash --public-host $PublicHost --out-dir (Join-Path $InstallDir "certs")
  } else {
    Write-Warning "No cert generator found — ensure certs/ exists before starting backend"
  }
}

$ws = "ws://${PublicHost}:${BackendPort}/ws/metrics"
$envPath = Join-Path $InstallDir ".env"
@"
# Generated by install-monitor.ps1 (v2.0 agent-initiated)
NEXT_PUBLIC_WS_URL=$ws
BACKEND_PORT=$BackendPort
DASHBOARD_PORT=$DashboardPort
GATEWAY_PORT=$GatewayPort
GATEWAY_ADVERTISE_HOST=$PublicHost
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath"
Write-Host "  Gateway = ${PublicHost}:${GatewayPort}"
Write-Host "  UI WS   = $ws"

$composeArgs = @("--project-directory", $InstallDir, "-f", (Join-Path $InstallDir "docker-compose.yml"))
if ($Demo) { $composeArgs = @("--profile", "demo") + $composeArgs }

if ($NoStart) {
  Write-Host "Skipping start. Run: docker compose $($composeArgs -join ' ') up -d --build"
  exit 0
}

Write-Host "Building and starting Pulsegrid Monitor…"
& docker compose @composeArgs up -d --build

Write-Host @"

Pulsegrid Monitor is up
  Dashboard:     http://${PublicHost}:${DashboardPort}
  Terminal:      http://${PublicHost}:${DashboardPort}/terminal
  Backend:       http://${PublicHost}:${BackendPort}/healthz
  Agent Gateway: ${PublicHost}:${GatewayPort} (TLS)
  CA cert:       $(Join-Path $InstallDir 'certs\ca.crt')

Add agents via UI, or:
  .\scripts\run-agent.ps1 -ServerId local-01 -Monitor ${PublicHost}:${GatewayPort} -Token pg_join_... -CaFile .\certs\ca.crt

"@
