# Pulsegrid Monitor — no-clone install (pull GHCR images only).
# Requires: Docker Desktop, openssl (Git for Windows includes it).
#
#   irm https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor-images.ps1 -OutFile $env:TEMP\pg-mon.ps1
#   powershell -ExecutionPolicy Bypass -File $env:TEMP\pg-mon.ps1 -PublicHost 192.168.0.230
param(
  [string]$PublicHost = $(if ($env:PUBLIC_HOST) { $env:PUBLIC_HOST } else { "localhost" }),
  [int]$BackendPort = 8080,
  [int]$DashboardPort = 3000,
  [int]$GatewayPort = 50051,
  [string]$InstallDir = "",
  [string]$Version = $(if ($env:PULSEGRID_VERSION) { $env:PULSEGRID_VERSION } else { "latest" }),
  [string]$ImageOwner = "sokmeankao",
  [string]$Repo = "SokmeanKao/Pulsegrid",
  [string]$Branch = "main",
  [switch]$NoStart
)

$ErrorActionPreference = "Stop"

if (-not $InstallDir) {
  $InstallDir = Join-Path $HOME "pulsegrid-monitor"
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "docker is required (Docker Desktop)"
}
docker compose version | Out-Null

$openssl = $null
foreach ($c in @(
  "openssl",
  "C:\Program Files\Git\usr\bin\openssl.exe",
  "C:\ProgramData\chocolatey\bin\openssl.exe"
)) {
  if ($c -eq "openssl") {
    $cmd = Get-Command openssl -ErrorAction SilentlyContinue
    if ($cmd) { $openssl = $cmd.Source; break }
  } elseif (Test-Path $c) { $openssl = $c; break }
}
if (-not $openssl) {
  throw "openssl is required (install Git for Windows)"
}

$raw = "https://raw.githubusercontent.com/$Repo/$Branch"
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $InstallDir "certs") | Out-Null

Write-Host "Downloading compose into $InstallDir"
Invoke-WebRequest -UseBasicParsing -Uri "$raw/docker-compose.monitor.yml" `
  -OutFile (Join-Path $InstallDir "docker-compose.yml")

# Inline cert generation (same as generate-monitor-certs.ps1)
$OutDir = Join-Path $InstallDir "certs"
$serverCrt = Join-Path $OutDir "server.crt"
if (-not (Test-Path $serverCrt)) {
  Write-Host "Generating CA + server cert for SAN=$PublicHost"
  & $openssl genrsa -out (Join-Path $OutDir "ca.key") 4096
  & $openssl req -x509 -new -nodes -key (Join-Path $OutDir "ca.key") -sha256 -days 3650 `
    -subj "/CN=Pulsegrid Local CA" -out (Join-Path $OutDir "ca.crt")
  & $openssl genrsa -out (Join-Path $OutDir "server.key") 2048
  & $openssl req -new -key (Join-Path $OutDir "server.key") -subj "/CN=$PublicHost" `
    -out (Join-Path $OutDir "server.csr")
  $san = "subjectAltName=DNS:localhost,IP:127.0.0.1"
  if ($PublicHost -match '^\d+\.\d+\.\d+\.\d+$') {
    $san += ",IP:$PublicHost"
  } else {
    $san += ",DNS:$PublicHost"
  }
  $ext = Join-Path $OutDir "san.ext"
  "$san`nextendedKeyUsage=serverAuth`n" | Set-Content -Path $ext -Encoding ascii
  & $openssl x509 -req -in (Join-Path $OutDir "server.csr") `
    -CA (Join-Path $OutDir "ca.crt") -CAkey (Join-Path $OutDir "ca.key") `
    -CAcreateserial -out $serverCrt -days 825 -sha256 -extfile $ext
  Remove-Item (Join-Path $OutDir "server.csr"), (Join-Path $OutDir "ca.srl"), $ext -ErrorAction SilentlyContinue
} else {
  Write-Host "Certs already exist in $OutDir"
}

$ws = "ws://${PublicHost}:${BackendPort}/ws/metrics"
$api = "http://${PublicHost}:${BackendPort}"
$envPath = Join-Path $InstallDir ".env"
@"
# Generated by install-monitor-images.ps1
GATEWAY_ADVERTISE_HOST=$PublicHost
BACKEND_PORT=$BackendPort
DASHBOARD_PORT=$DashboardPort
GATEWAY_PORT=$GatewayPort
PULSEGRID_VERSION=$Version
PULSEGRID_IMAGE_OWNER=$ImageOwner
PULSEGRID_BACKEND_PORT=$BackendPort
PULSEGRID_API_URL=$api
PULSEGRID_WS_URL=$ws
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath"

if ($NoStart) {
  Write-Host "Skipping start. Run: cd `"$InstallDir`"; docker compose pull; docker compose up -d"
  exit 0
}

Write-Host "Pulling images (version=$Version)…"
Push-Location $InstallDir
try {
  docker compose pull
  Write-Host "Starting Pulsegrid Monitor…"
  docker compose up -d
} finally {
  Pop-Location
}

Write-Host @"

Pulsegrid Monitor is up (image mode)
  Dashboard:     http://${PublicHost}:${DashboardPort}
  Terminal:      http://${PublicHost}:${DashboardPort}/terminal
  Backend:       http://${PublicHost}:${BackendPort}/healthz
  Agent Gateway: ${PublicHost}:${GatewayPort} (TLS)
  CA cert:       $(Join-Path $InstallDir 'certs\ca.crt')
  Install dir:   $InstallDir

Add agents from the UI (+ Add Agent).

"@
