#!/usr/bin/env bash
# Pulsegrid Monitor one-line installer (Linux / WSL).
# Installs DB + backend + dashboard via Docker Compose.
# Agents are installed separately with install-agent.sh.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor.sh \
#     | sudo bash -s -- --agents "kali-01:192.168.150.131:50051"
set -euo pipefail

REPO="${GITHUB_REPO:-SokmeanKao/Pulsegrid}"
REPO_URL="${REPO_URL:-https://github.com/${REPO}.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/pulsegrid}"
BRANCH="${BRANCH:-main}"
AGENTS="${AGENTS:-}"
PUBLIC_HOST="${PUBLIC_HOST:-localhost}"
BACKEND_PORT="${BACKEND_PORT:-8080}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
DEMO=0
START=1

usage() {
  cat <<'EOF'
Install Pulsegrid Monitor (TimescaleDB + backend + UI) with Docker Compose.

Agents are NOT included — install them on each host with install-agent.sh.

Options:
  --agents LIST        AGENTS=id:host:port,... (backend dials these)
  --public-host HOST   Hostname/IP browsers use for WebSocket (default: localhost)
  --backend-port N     Host port for backend (default 8080)
  --dashboard-port N   Host port for UI (default 3000)
  --install-dir PATH   Clone/install path (default /opt/pulsegrid)
  --branch NAME        Git branch (default main)
  --demo               Also start in-compose demo agents (container metrics only)
  --no-start           Clone/configure only; do not docker compose up
  -h, --help           Show help

Env:
  GITHUB_REPO, REPO_URL, INSTALL_DIR, BRANCH, AGENTS, PUBLIC_HOST,
  BACKEND_PORT, DASHBOARD_PORT
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agents) AGENTS="${2:-}"; shift 2 ;;
    --public-host) PUBLIC_HOST="${2:-}"; shift 2 ;;
    --backend-port) BACKEND_PORT="${2:-}"; shift 2 ;;
    --dashboard-port) DASHBOARD_PORT="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --branch) BRANCH="${2:-}"; shift 2 ;;
    --demo) DEMO=1; shift ;;
    --no-start) START=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "error: run as root (sudo)" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "error: docker compose plugin is required" >&2
  exit 1
fi

if [[ -d "${INSTALL_DIR}/.git" ]]; then
  echo "→ Updating ${INSTALL_DIR} (${BRANCH})…"
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$INSTALL_DIR" checkout "$BRANCH"
  git -C "$INSTALL_DIR" pull --ff-only origin "$BRANCH" || true
else
  echo "→ Cloning ${REPO_URL} → ${INSTALL_DIR}"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi

WS_URL="ws://${PUBLIC_HOST}:${BACKEND_PORT}/ws/metrics"
ENV_FILE="${INSTALL_DIR}/.env"

if [[ "$DEMO" -eq 1 && -z "$AGENTS" ]]; then
  AGENTS="web-01:agent-web-01:50051,db-01:agent-db-01:50052"
fi

cat >"$ENV_FILE" <<EOF
# Generated by install-monitor.sh
AGENTS=${AGENTS}
NEXT_PUBLIC_WS_URL=${WS_URL}
BACKEND_PORT=${BACKEND_PORT}
DASHBOARD_PORT=${DASHBOARD_PORT}
EOF

echo "→ Wrote ${ENV_FILE}"
echo "   AGENTS=${AGENTS:-<none — add hosts later>}"
echo "   UI WS  =${WS_URL}"

COMPOSE=(docker compose --project-directory "$INSTALL_DIR" -f "${INSTALL_DIR}/docker-compose.yml")
if [[ "$DEMO" -eq 1 ]]; then
  COMPOSE+=(--profile demo)
fi

if [[ "$START" -eq 0 ]]; then
  echo "→ Skipping start (--no-start). Run:"
  echo "   ${COMPOSE[*]} up -d --build"
  exit 0
fi

echo "→ Building and starting Pulsegrid Monitor…"
"${COMPOSE[@]}" up -d --build

cat <<EOF

✓ Pulsegrid Monitor is up

  Dashboard:  http://${PUBLIC_HOST}:${DASHBOARD_PORT}
  Terminal:   http://${PUBLIC_HOST}:${DASHBOARD_PORT}/terminal
  Backend:    http://${PUBLIC_HOST}:${BACKEND_PORT}/healthz
  Install dir:${INSTALL_DIR}

Install agents on each machine you want to monitor:

  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install-agent.sh \\
    | sudo bash -s -- --server-id HOST_ID

Then set AGENTS in ${ENV_FILE} and restart backend:

  cd ${INSTALL_DIR}
  docker compose up -d --build backend

EOF
