#!/usr/bin/env bash
# Pulsegrid Monitor — no-clone install (one app image + Timescale).
#
#   curl -fsSL https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor-images.sh \
#     | bash -s -- --public-host 192.168.0.230
set -euo pipefail

REPO="${GITHUB_REPO:-SokmeanKao/Pulsegrid}"
BRANCH="${BRANCH:-main}"
RAW="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/pulsegrid-monitor}"
PUBLIC_HOST="${PUBLIC_HOST:-localhost}"
HTTP_PORT="${HTTP_PORT:-80}"
GATEWAY_PORT="${GATEWAY_PORT:-50051}"
PULSEGRID_VERSION="${PULSEGRID_VERSION:-latest}"
PULSEGRID_IMAGE_OWNER="${PULSEGRID_IMAGE_OWNER:-sokmeankao}"
START=1

usage() {
  cat <<'EOF'
Install Pulsegrid Monitor (Timescale + one unified UI/API/Gateway container).

Options:
  --public-host HOST     IP/DNS for TLS SAN + advertise (default: localhost)
  --http-port N          Public HTTP port (default 80 → UI+API+WS)
  --gateway-port N       Agent Gateway TLS port (default 50051)
  --install-dir PATH     Install directory (default: ~/pulsegrid-monitor)
  --version TAG          Image tag (default: latest) e.g. v2.3.0
  --image-owner NAME     GHCR owner (default: sokmeankao)
  --no-start             Download/configure only
  -h, --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --public-host) PUBLIC_HOST="${2:-}"; shift 2 ;;
    --http-port) HTTP_PORT="${2:-}"; shift 2 ;;
    --backend-port|--dashboard-port)
      echo "note: ignored (unified image); use --http-port" >&2
      shift 2
      ;;
    --gateway-port) GATEWAY_PORT="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --version) PULSEGRID_VERSION="${2:-}"; shift 2 ;;
    --image-owner) PULSEGRID_IMAGE_OWNER="${2:-}"; shift 2 ;;
    --no-start) START=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

command -v docker >/dev/null || { echo "error: docker required" >&2; exit 1; }
docker compose version >/dev/null || { echo "error: docker compose required" >&2; exit 1; }
command -v openssl >/dev/null || { echo "error: openssl required" >&2; exit 1; }
command -v curl >/dev/null || { echo "error: curl required" >&2; exit 1; }

mkdir -p "$INSTALL_DIR/certs"
cd "$INSTALL_DIR"

echo "→ Downloading compose into ${INSTALL_DIR}"
curl -fsSL "${RAW}/docker-compose.monitor.yml" -o docker-compose.yml
curl -fsSL "${RAW}/scripts/generate-monitor-certs.sh" -o generate-monitor-certs.sh
chmod +x generate-monitor-certs.sh
# Remove stale nginx config from older installs
rm -f nginx.conf

bash ./generate-monitor-certs.sh --public-host "$PUBLIC_HOST" --out-dir "${INSTALL_DIR}/certs"

cat >.env <<EOF
# Generated by install-monitor-images.sh (unified monitor image)
GATEWAY_ADVERTISE_HOST=${PUBLIC_HOST}
HTTP_PORT=${HTTP_PORT}
GATEWAY_PORT=${GATEWAY_PORT}
PULSEGRID_VERSION=${PULSEGRID_VERSION}
PULSEGRID_IMAGE_OWNER=${PULSEGRID_IMAGE_OWNER}
EOF

echo "→ Wrote ${INSTALL_DIR}/.env"

if [[ "$START" -eq 0 ]]; then
  echo "→ Skipping start. Run: cd ${INSTALL_DIR} && docker compose pull && docker compose up -d"
  exit 0
fi

echo "→ Pulling images (version=${PULSEGRID_VERSION})…"
docker compose pull
echo "→ Starting Pulsegrid Monitor…"
docker compose up -d

HTTP_DISP="${PUBLIC_HOST}"
[[ "$HTTP_PORT" != "80" ]] && HTTP_DISP="${PUBLIC_HOST}:${HTTP_PORT}"

cat <<EOF

✓ Pulsegrid Monitor is up (unified image)

  Dashboard:      http://${HTTP_DISP}/terminal/
  Health:         http://${HTTP_DISP}/healthz
  Agent Gateway:  ${PUBLIC_HOST}:${GATEWAY_PORT} (TLS)
  CA cert:        ${INSTALL_DIR}/certs/ca.crt
  Install dir:    ${INSTALL_DIR}

Containers: db + monitor (UI+API+Gateway in one)

EOF
