# Pulsegrid Monitor — complete no-clone install (compose + .env; TLS auto in container).
#   irm https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor-images.ps1 -OutFile $env:TEMP\pg-mon.ps1
#   powershell -ExecutionPolicy Bypass -File $env:TEMP\pg-mon.ps1 -PublicHost 192.168.0.230
param(
  [string]$PublicHost = $(if ($env:PUBLIC_HOST) { $env:PUBLIC_HOST } else { "localhost" }),
  [int]$HttpPort = 8080,
  [int]$GatewayPort = 50051,
  [string]$InstallDir = "",
  [string]$Version = $(if ($env:PULSEGRID_VERSION) { $env:PULSEGRID_VERSION } else { "latest" }),
  [string]$ImageOwner = "sokmeankao",
  [string]$Repo = "SokmeanKao/Pulsegrid",
  [string]$Branch = "main",
  [switch]$NoStart
)

$ErrorActionPreference = "Stop"

if (-not $InstallDir) {
  $InstallDir = Join-Path $HOME "pulsegrid-monitor"
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "docker is required (Docker Desktop)"
}
docker compose version | Out-Null

$raw = "https://raw.githubusercontent.com/$Repo/$Branch"
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

Write-Host "Downloading compose into $InstallDir"
Invoke-WebRequest -UseBasicParsing -Uri "$raw/docker-compose.monitor.yml" `
  -OutFile (Join-Path $InstallDir "docker-compose.yml")
Remove-Item (Join-Path $InstallDir "nginx.conf") -ErrorAction SilentlyContinue

$envPath = Join-Path $InstallDir ".env"
@"
# Generated by install-monitor-images.ps1 — TLS certs auto-created inside the monitor container
GATEWAY_ADVERTISE_HOST=$PublicHost
HTTP_PORT=$HttpPort
GATEWAY_PORT=$GatewayPort
PULSEGRID_VERSION=$Version
PULSEGRID_IMAGE_OWNER=$ImageOwner
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath"

if ($NoStart) {
  Write-Host "Skipping start. Run: cd `"$InstallDir`"; docker compose pull; docker compose up -d"
  exit 0
}

Push-Location $InstallDir
try {
  docker compose pull
  docker compose up -d
} finally {
  Pop-Location
}

$httpDisp = "${PublicHost}:${HttpPort}"
if ($HttpPort -eq 80) { $httpDisp = $PublicHost }

Write-Host @"

Pulsegrid Monitor is up
  Dashboard:     http://${httpDisp}/terminal/
  Health:        http://${httpDisp}/healthz
  Agent Gateway: ${PublicHost}:${GatewayPort} (TLS)
  Install dir:   $InstallDir

Export CA for agents:
  cd `"$InstallDir`"; docker compose cp monitor:/certs/ca.crt .\ca.crt

"@
