#!/usr/bin/env bash
# Pulsegrid Monitor — no-clone install (pull GHCR images only).
#
# Linux / WSL / Git Bash (Docker required; sudo NOT required if docker works for you):
#   curl -fsSL https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor-images.sh \
#     | bash -s -- --public-host 192.168.0.230
#
# Windows PowerShell (preferred on Windows):
#   irm https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor-images.ps1 -OutFile $env:TEMP\pg-mon.ps1
#   powershell -File $env:TEMP\pg-mon.ps1 -PublicHost 192.168.0.230
set -euo pipefail

REPO="${GITHUB_REPO:-SokmeanKao/Pulsegrid}"
BRANCH="${BRANCH:-main}"
RAW="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
INSTALL_DIR="${INSTALL_DIR:-${HOME}/pulsegrid-monitor}"
PUBLIC_HOST="${PUBLIC_HOST:-localhost}"
BACKEND_PORT="${BACKEND_PORT:-8080}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
GATEWAY_PORT="${GATEWAY_PORT:-50051}"
PULSEGRID_VERSION="${PULSEGRID_VERSION:-latest}"
PULSEGRID_IMAGE_OWNER="${PULSEGRID_IMAGE_OWNER:-sokmeankao}"
START=1

usage() {
  cat <<'EOF'
Install Pulsegrid Monitor from published Docker images (no git clone).

Options:
  --public-host HOST     IP/DNS for UI + TLS SAN + advertise (default: localhost)
  --backend-port N       API/WS host port (default 8080)
  --dashboard-port N     UI host port (default 3000)
  --gateway-port N       Agent Gateway TLS port (default 50051)
  --install-dir PATH     Install directory (default: ~/pulsegrid-monitor)
  --version TAG          Image tag (default: latest) e.g. v2.2.0
  --image-owner NAME     GHCR owner (default: sokmeankao)
  --no-start             Download/configure only
  -h, --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --public-host) PUBLIC_HOST="${2:-}"; shift 2 ;;
    --backend-port) BACKEND_PORT="${2:-}"; shift 2 ;;
    --dashboard-port) DASHBOARD_PORT="${2:-}"; shift 2 ;;
    --gateway-port) GATEWAY_PORT="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --version) PULSEGRID_VERSION="${2:-}"; shift 2 ;;
    --image-owner) PULSEGRID_IMAGE_OWNER="${2:-}"; shift 2 ;;
    --no-start) START=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "error: docker compose plugin is required" >&2
  exit 1
fi
if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate Monitor TLS certs" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "error: curl is required" >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR/certs"
cd "$INSTALL_DIR"

echo "→ Downloading compose + cert script into ${INSTALL_DIR}"
curl -fsSL "${RAW}/docker-compose.monitor.yml" -o docker-compose.yml
curl -fsSL "${RAW}/scripts/generate-monitor-certs.sh" -o generate-monitor-certs.sh
chmod +x generate-monitor-certs.sh

bash ./generate-monitor-certs.sh --public-host "$PUBLIC_HOST" --out-dir "${INSTALL_DIR}/certs"

WS_URL="ws://${PUBLIC_HOST}:${BACKEND_PORT}/ws/metrics"
API_URL="http://${PUBLIC_HOST}:${BACKEND_PORT}"

cat >.env <<EOF
# Generated by install-monitor-images.sh
GATEWAY_ADVERTISE_HOST=${PUBLIC_HOST}
BACKEND_PORT=${BACKEND_PORT}
DASHBOARD_PORT=${DASHBOARD_PORT}
GATEWAY_PORT=${GATEWAY_PORT}
PULSEGRID_VERSION=${PULSEGRID_VERSION}
PULSEGRID_IMAGE_OWNER=${PULSEGRID_IMAGE_OWNER}
PULSEGRID_BACKEND_PORT=${BACKEND_PORT}
PULSEGRID_API_URL=${API_URL}
PULSEGRID_WS_URL=${WS_URL}
EOF

echo "→ Wrote ${INSTALL_DIR}/.env"

if [[ "$START" -eq 0 ]]; then
  echo "→ Skipping start. Run:"
  echo "   cd ${INSTALL_DIR} && docker compose pull && docker compose up -d"
  exit 0
fi

echo "→ Pulling images (version=${PULSEGRID_VERSION})…"
docker compose pull

echo "→ Starting Pulsegrid Monitor…"
docker compose up -d

cat <<EOF

✓ Pulsegrid Monitor is up (image mode)

  Dashboard:      http://${PUBLIC_HOST}:${DASHBOARD_PORT}
  Terminal:       http://${PUBLIC_HOST}:${DASHBOARD_PORT}/terminal
  Backend:        http://${PUBLIC_HOST}:${BACKEND_PORT}/healthz
  Agent Gateway:  ${PUBLIC_HOST}:${GATEWAY_PORT} (TLS)
  CA cert:        ${INSTALL_DIR}/certs/ca.crt
  Install dir:    ${INSTALL_DIR}

Add agents from the UI (+ Add Agent).

EOF
