# Pulsegrid Monitor installer for Windows (Docker Desktop required).
# Agents stay separate — use scripts/run-agent.ps1 or install-agent.sh on Linux hosts.
param(
  [string]$Agents = "",
  [string]$PublicHost = "localhost",
  [int]$BackendPort = 8080,
  [int]$DashboardPort = 3000,
  [string]$InstallDir = "",
  [switch]$Demo,
  [switch]$NoStart
)

$ErrorActionPreference = "Stop"

if (-not $InstallDir) {
  $InstallDir = Split-Path -Parent $PSScriptRoot
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "docker is required (Docker Desktop)"
}

docker compose version | Out-Null

if ($Demo -and -not $Agents) {
  $Agents = "web-01:agent-web-01:50051,db-01:agent-db-01:50052"
}

$ws = "ws://${PublicHost}:${BackendPort}/ws/metrics"
$envPath = Join-Path $InstallDir ".env"
@"
# Generated by install-monitor.ps1
AGENTS=$Agents
NEXT_PUBLIC_WS_URL=$ws
BACKEND_PORT=$BackendPort
DASHBOARD_PORT=$DashboardPort
"@ | Set-Content -Path $envPath -Encoding utf8

Write-Host "Wrote $envPath"
Write-Host "  AGENTS=$Agents"
Write-Host "  UI WS =$ws"

$composeArgs = @("--project-directory", $InstallDir, "-f", (Join-Path $InstallDir "docker-compose.yml"))
if ($Demo) { $composeArgs = @("--profile", "demo") + $composeArgs }

if ($NoStart) {
  Write-Host "Skipping start. Run: docker compose $($composeArgs -join ' ') up -d --build"
  exit 0
}

Write-Host "Building and starting Pulsegrid Monitor…"
& docker compose @composeArgs up -d --build

Write-Host @"

Pulsegrid Monitor is up
  Dashboard: http://${PublicHost}:${DashboardPort}
  Terminal:  http://${PublicHost}:${DashboardPort}/terminal
  Backend:   http://${PublicHost}:${BackendPort}/healthz

Agents run separately, e.g.:
  .\scripts\run-agent.ps1 -ServerId local-01
  # then AGENTS=local-01:host.docker.internal:50051 in .env

"@
