#!/usr/bin/env bash
# Pulsegrid Monitor one-line installer (Linux / WSL).
# Installs DB + backend + dashboard via Docker Compose.
# Agents dial the Monitor Agent Gateway (TLS :50051).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/SokmeanKao/Pulsegrid/main/scripts/install-monitor.sh \
#     | sudo bash -s -- --public-host 192.168.150.10
set -euo pipefail

REPO="${GITHUB_REPO:-SokmeanKao/Pulsegrid}"
REPO_URL="${REPO_URL:-https://github.com/${REPO}.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/pulsegrid}"
BRANCH="${BRANCH:-main}"
PUBLIC_HOST="${PUBLIC_HOST:-localhost}"
BACKEND_PORT="${BACKEND_PORT:-8080}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3000}"
GATEWAY_PORT="${GATEWAY_PORT:-50051}"
DEMO=0
START=1

usage() {
  cat <<'EOF'
Install Pulsegrid Monitor (TimescaleDB + backend + UI + Agent Gateway).

Agents are NOT included — install them on each host with install-agent.sh
(--monitor, --token, --ca).

Options:
  --public-host HOST   Hostname/IP for UI WS + TLS SAN + advertise (default: localhost)
  --backend-port N     Host port for API/WS (default 8080)
  --dashboard-port N   Host port for UI (default 3000)
  --gateway-port N     Host port for Agent Gateway TLS (default 50051)
  --install-dir PATH   Clone/install path (default /opt/pulsegrid)
  --branch NAME        Git branch (default main)
  --demo               Also start in-compose demo agents (client mode)
  --no-start           Clone/configure only; do not docker compose up
  -h, --help           Show help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --public-host) PUBLIC_HOST="${2:-}"; shift 2 ;;
    --backend-port) BACKEND_PORT="${2:-}"; shift 2 ;;
    --dashboard-port) DASHBOARD_PORT="${2:-}"; shift 2 ;;
    --gateway-port) GATEWAY_PORT="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --branch) BRANCH="${2:-}"; shift 2 ;;
    --demo) DEMO=1; shift ;;
    --no-start) START=0; shift ;;
    --agents)
      echo "error: --agents was removed in v2.0 (agents dial the Monitor)" >&2
      exit 1
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "error: run as root (sudo)" >&2
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required" >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "error: docker compose plugin is required" >&2
  exit 1
fi

if [[ -d "${INSTALL_DIR}/.git" ]]; then
  echo "→ Updating ${INSTALL_DIR} (${BRANCH})…"
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$INSTALL_DIR" checkout "$BRANCH"
  git -C "$INSTALL_DIR" pull --ff-only origin "$BRANCH" || true
else
  echo "→ Cloning ${REPO_URL} → ${INSTALL_DIR}"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi

WS_URL="ws://${PUBLIC_HOST}:${BACKEND_PORT}/ws/metrics"
ENV_FILE="${INSTALL_DIR}/.env"

bash "${INSTALL_DIR}/scripts/generate-monitor-certs.sh" \
  --public-host "$PUBLIC_HOST" \
  --out-dir "${INSTALL_DIR}/certs"

cat >"$ENV_FILE" <<EOF
# Generated by install-monitor.sh (v2.0 agent-initiated)
NEXT_PUBLIC_WS_URL=${WS_URL}
BACKEND_PORT=${BACKEND_PORT}
DASHBOARD_PORT=${DASHBOARD_PORT}
GATEWAY_PORT=${GATEWAY_PORT}
GATEWAY_ADVERTISE_HOST=${PUBLIC_HOST}
EOF

echo "→ Wrote ${ENV_FILE}"
echo "   Gateway advertise = ${PUBLIC_HOST}:${GATEWAY_PORT}"
echo "   UI WS             = ${WS_URL}"

COMPOSE=(docker compose --project-directory "$INSTALL_DIR" -f "${INSTALL_DIR}/docker-compose.yml")
if [[ "$DEMO" -eq 1 ]]; then
  COMPOSE+=(--profile demo)
fi

if [[ "$START" -eq 0 ]]; then
  echo "→ Skipping start (--no-start). Run:"
  echo "   ${COMPOSE[*]} up -d --build"
  exit 0
fi

echo "→ Building and starting Pulsegrid Monitor…"
"${COMPOSE[@]}" up -d --build

cat <<EOF

✓ Pulsegrid Monitor is up

  Dashboard:      http://${PUBLIC_HOST}:${DASHBOARD_PORT}
  Terminal:       http://${PUBLIC_HOST}:${DASHBOARD_PORT}/terminal
  Backend:        http://${PUBLIC_HOST}:${BACKEND_PORT}/healthz
  Agent Gateway:  ${PUBLIC_HOST}:${GATEWAY_PORT} (TLS)
  CA cert:        ${INSTALL_DIR}/certs/ca.crt
  Install dir:    ${INSTALL_DIR}

Add an agent from the UI (Add Agent), or:

  curl -fsSL https://raw.githubusercontent.com/${REPO}/main/scripts/install-agent.sh \\
    | sudo bash -s -- --server-id HOST_ID \\
        --monitor ${PUBLIC_HOST}:${GATEWAY_PORT} \\
        --token pg_join_… \\
        --ca /etc/pulsegrid/ca.crt

EOF
